# ZapStop AWS Deployment Script (PowerShell)
# This script deploys the complete ZapStop application to AWS

param(
    [string]$Stage = "dev",
    [string]$Region = "me-central-1",
    [string]$Profile = "default"
)

# Colors for output
$Red = "Red"
$Green = "Green"
$Yellow = "Yellow"
$Blue = "Blue"

Write-Host "ZapStop AWS Deployment Script" -ForegroundColor $Blue
Write-Host "==================================" -ForegroundColor $Blue
Write-Host "Stage: $Stage" -ForegroundColor $Green
Write-Host "Region: $Region" -ForegroundColor $Green
Write-Host "Profile: $Profile" -ForegroundColor $Green
Write-Host ""

# Check prerequisites
Write-Host "Checking prerequisites..." -ForegroundColor $Yellow

# Check AWS CLI
try {
    & "C:\Program Files\Amazon\AWSCLIV2\aws.exe" --version | Out-Null
    Write-Host "AWS CLI found" -ForegroundColor $Green
} catch {
    Write-Host "AWS CLI not found. Please install AWS CLI." -ForegroundColor $Red
    exit 1
}

# Check if AWS is configured
try {
    & "C:\Program Files\Amazon\AWSCLIV2\aws.exe" sts get-caller-identity --profile $Profile | Out-Null
    Write-Host "AWS CLI configured for profile '$Profile'" -ForegroundColor $Green
} catch {
    Write-Host "AWS CLI not configured for profile '$Profile'. Please run 'aws configure'." -ForegroundColor $Red
    exit 1
}

# Check Serverless Framework
try {
    serverless --version | Out-Null
    Write-Host "Serverless Framework found" -ForegroundColor $Green
} catch {
    Write-Host "Installing Serverless Framework..." -ForegroundColor $Yellow
    npm install -g serverless
    npm install -g serverless-python-requirements
}

Write-Host "Prerequisites check passed" -ForegroundColor $Green

# Set AWS profile
$env:AWS_PROFILE = $Profile

# Step 1: Deploy Backend Infrastructure
Write-Host "Step 1: Deploying Backend Infrastructure..." -ForegroundColor $Yellow
Set-Location aws-infrastructure

# Install dependencies
npm install

# Deploy with Serverless Framework using simple configuration
serverless deploy --config serverless-simple.yml --stage $Stage --region $Region --verbose

# Get deployment outputs
Write-Host "Getting deployment outputs..." -ForegroundColor $Yellow

$API_URL = & "C:\Program Files\Amazon\AWSCLIV2\aws.exe" cloudformation describe-stacks --stack-name "zapstop-api-$Stage" --region $Region --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' --output text
$AURORA_ENDPOINT = & "C:\Program Files\Amazon\AWSCLIV2\aws.exe" cloudformation describe-stacks --stack-name "zapstop-api-$Stage" --region $Region --query 'Stacks[0].Outputs[?OutputKey==`RDSInstanceEndpoint`].OutputValue' --output text

Write-Host "Backend deployed successfully!" -ForegroundColor $Green
Write-Host "API URL: $API_URL" -ForegroundColor $Green
Write-Host "Aurora Endpoint: $AURORA_ENDPOINT" -ForegroundColor $Green

Set-Location ..

# Step 2: Update Frontend Configuration
Write-Host "Step 2: Updating Frontend Configuration..." -ForegroundColor $Yellow

# Create environment file for frontend
$envContent = @"
# ZapStop Frontend Environment Configuration
# Generated by deployment script

# API Configuration
NEXT_PUBLIC_API_URL=$API_URL

# Application Configuration
NEXT_PUBLIC_APP_NAME=ZapStop
NEXT_PUBLIC_APP_VERSION=1.0.0
NEXT_PUBLIC_STAGE=$Stage
NEXT_PUBLIC_REGION=$Region
"@

$envContent | Out-File -FilePath ".env.local" -Encoding UTF8

Write-Host "Frontend configuration updated" -ForegroundColor $Green

# Step 3: Test Backend Deployment
Write-Host "Step 3: Testing Backend Deployment..." -ForegroundColor $Yellow

# Test health endpoint
Write-Host "Testing health endpoint..."
try {
    $healthResponse = Invoke-WebRequest -Uri "$API_URL/health" -Method GET -UseBasicParsing
    if ($healthResponse.StatusCode -eq 200) {
        Write-Host "Health check passed" -ForegroundColor $Green
    } else {
        Write-Host "Health check failed (HTTP $($healthResponse.StatusCode))" -ForegroundColor $Red
    }
} catch {
    Write-Host "Health check failed: $($_.Exception.Message)" -ForegroundColor $Red
    Write-Host "Check CloudWatch logs for details" -ForegroundColor $Yellow
    Write-Host "Logs: aws logs describe-log-groups --log-group-name-prefix '/aws/lambda/zapstop' --region $Region" -ForegroundColor $Green
}

# Test API docs
Write-Host "Testing API documentation..."
try {
    $docsResponse = Invoke-WebRequest -Uri "$API_URL/docs" -Method GET -UseBasicParsing
    if ($docsResponse.StatusCode -eq 200) {
        Write-Host "API documentation accessible" -ForegroundColor $Green
    } else {
        Write-Host "API documentation not accessible (HTTP $($docsResponse.StatusCode))" -ForegroundColor $Yellow
    }
} catch {
    Write-Host "API documentation not accessible: $($_.Exception.Message)" -ForegroundColor $Yellow
}

# Step 4: Database Migration Instructions
Write-Host "Step 4: Database Migration" -ForegroundColor $Yellow
Write-Host "To complete the setup, you need to run database migrations:" -ForegroundColor $Blue
Write-Host ""
Write-Host "1. Install Alembic: pip install alembic" -ForegroundColor $Green
Write-Host "2. Configure database URL: `$env:DATABASE_URL='postgresql://username:password@$AURORA_ENDPOINT:5432/zapstop'" -ForegroundColor $Green
Write-Host "3. Run migrations: cd backend; alembic upgrade head" -ForegroundColor $Green
Write-Host ""

# Step 5: Build and Deploy Frontend
Write-Host "Step 5: Building Frontend..." -ForegroundColor $Yellow

# Install frontend dependencies
npm install

# Build frontend
npm run build

Write-Host "Frontend built successfully" -ForegroundColor $Green

# Step 6: Deployment Summary
Write-Host ""
Write-Host "Deployment Summary:" -ForegroundColor $Blue
Write-Host "Lambda function deployed"
Write-Host "Aurora Serverless v2 cluster created"
Write-Host "API Gateway configured"
Write-Host "Secrets Manager configured"
Write-Host "Frontend configured for AWS"
Write-Host "Frontend built successfully"
Write-Host ""

Write-Host "Next Steps:" -ForegroundColor $Blue
Write-Host "1. Run database migrations (see instructions above)"
Write-Host "2. Deploy frontend to Vercel/Netlify with the new API URL"
Write-Host "3. Test all functionality"
Write-Host "4. Configure monitoring and alerting"
Write-Host ""

Write-Host "Useful Commands:" -ForegroundColor $Blue
Write-Host "View Lambda logs: serverless logs -f api --stage $Stage --region $Region" -ForegroundColor $Green
Write-Host "Remove stack: serverless remove --stage $Stage --region $Region" -ForegroundColor $Green
Write-Host "Update stack: serverless deploy --stage $Stage --region $Region" -ForegroundColor $Green
Write-Host "Test API: curl $API_URL/health" -ForegroundColor $Green
Write-Host ""

Write-Host "Deployment completed successfully!" -ForegroundColor $Green
