#!/bin/bash

# ZapStop AWS Deployment Script
# This script deploys the complete ZapStop application to AWS

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
STAGE=${1:-dev}
REGION=${2:-me-central-1}
PROFILE=${3:-default}

echo -e "${BLUE}🚀 ZapStop AWS Deployment Script${NC}"
echo -e "${BLUE}==================================${NC}"
echo -e "Stage: ${GREEN}$STAGE${NC}"
echo -e "Region: ${GREEN}$REGION${NC}"
echo -e "Profile: ${GREEN}$PROFILE${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}📋 Checking prerequisites...${NC}"

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo -e "${RED}❌ AWS CLI not found. Please install AWS CLI.${NC}"
    exit 1
fi

# Check if AWS is configured
if ! aws sts get-caller-identity --profile $PROFILE &> /dev/null; then
    echo -e "${RED}❌ AWS CLI not configured for profile '$PROFILE'. Please run 'aws configure'.${NC}"
    exit 1
fi

# Check Serverless Framework
if ! command -v serverless &> /dev/null; then
    echo -e "${YELLOW}📦 Installing Serverless Framework...${NC}"
    npm install -g serverless
    npm install -g serverless-python-requirements
fi

echo -e "${GREEN}✅ Prerequisites check passed${NC}"

# Set AWS profile
export AWS_PROFILE=$PROFILE

# Step 1: Deploy Backend Infrastructure
echo -e "${YELLOW}🏗️  Step 1: Deploying Backend Infrastructure...${NC}"
cd aws-infrastructure

# Install dependencies
npm install

# Deploy with Serverless Framework
serverless deploy \
    --stage $STAGE \
    --region $REGION \
    --verbose

# Get deployment outputs
echo -e "${YELLOW}📊 Getting deployment outputs...${NC}"

API_URL=$(aws cloudformation describe-stacks \
    --stack-name zapstop-api-$STAGE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiGatewayUrl`].OutputValue' \
    --output text)

AURORA_ENDPOINT=$(aws cloudformation describe-stacks \
    --stack-name zapstop-api-$STAGE \
    --region $REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`RDSInstanceEndpoint`].OutputValue' \
    --output text)

echo -e "${GREEN}✅ Backend deployed successfully!${NC}"
echo -e "API URL: ${GREEN}$API_URL${NC}"
echo -e "Aurora Endpoint: ${GREEN}$AURORA_ENDPOINT${NC}"

cd ..

# Step 2: Update Frontend Configuration
echo -e "${YELLOW}🎨 Step 2: Updating Frontend Configuration...${NC}"

# Create environment file for frontend
cat > .env.local << EOF
# ZapStop Frontend Environment Configuration
# Generated by deployment script

# API Configuration
NEXT_PUBLIC_API_URL=$API_URL

# Application Configuration
NEXT_PUBLIC_APP_NAME=ZapStop
NEXT_PUBLIC_APP_VERSION=1.0.0
NEXT_PUBLIC_STAGE=$STAGE
NEXT_PUBLIC_REGION=$REGION
EOF

echo -e "${GREEN}✅ Frontend configuration updated${NC}"

# Step 3: Test Backend Deployment
echo -e "${YELLOW}🧪 Step 3: Testing Backend Deployment...${NC}"

# Test health endpoint
echo -e "Testing health endpoint..."
HEALTH_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL/health" || echo "000")

if [ "$HEALTH_RESPONSE" = "200" ]; then
    echo -e "${GREEN}✅ Health check passed${NC}"
else
    echo -e "${RED}❌ Health check failed (HTTP $HEALTH_RESPONSE)${NC}"
    echo -e "${YELLOW}💡 Check CloudWatch logs for details${NC}"
    echo -e "Logs: ${GREEN}aws logs describe-log-groups --log-group-name-prefix '/aws/lambda/zapstop' --region $REGION${NC}"
fi

# Test API docs
echo -e "Testing API documentation..."
DOCS_RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL/docs" || echo "000")

if [ "$DOCS_RESPONSE" = "200" ]; then
    echo -e "${GREEN}✅ API documentation accessible${NC}"
else
    echo -e "${YELLOW}⚠️  API documentation not accessible (HTTP $DOCS_RESPONSE)${NC}"
fi

# Step 4: Database Migration Instructions
echo -e "${YELLOW}🗄️  Step 4: Database Migration${NC}"
echo -e "${BLUE}To complete the setup, you need to run database migrations:${NC}"
echo ""
echo -e "1. Install Alembic: ${GREEN}pip install alembic${NC}"
echo -e "2. Configure database URL: ${GREEN}export DATABASE_URL='postgresql://username:password@$AURORA_ENDPOINT:5432/zapstop'${NC}"
echo -e "3. Run migrations: ${GREEN}cd backend && alembic upgrade head${NC}"
echo ""

# Step 5: Build and Deploy Frontend
echo -e "${YELLOW}🎨 Step 5: Building Frontend...${NC}"

# Install frontend dependencies
npm install

# Build frontend
npm run build

echo -e "${GREEN}✅ Frontend built successfully${NC}"

# Step 6: Deployment Summary
echo ""
echo -e "${BLUE}🎉 Deployment Summary:${NC}"
echo -e "✅ Lambda function deployed"
echo -e "✅ Aurora Serverless v2 cluster created"
echo -e "✅ API Gateway configured"
echo -e "✅ Secrets Manager configured"
echo -e "✅ Frontend configured for AWS"
echo -e "✅ Frontend built successfully"
echo ""

echo -e "${BLUE}📋 Next Steps:${NC}"
echo -e "1. Run database migrations (see instructions above)"
echo -e "2. Deploy frontend to Vercel/Netlify with the new API URL"
echo -e "3. Test all functionality"
echo -e "4. Configure monitoring and alerting"
echo ""

echo -e "${BLUE}🔗 Useful Commands:${NC}"
echo -e "View Lambda logs: ${GREEN}serverless logs -f api --stage $STAGE --region $REGION${NC}"
echo -e "Remove stack: ${GREEN}serverless remove --stage $STAGE --region $REGION${NC}"
echo -e "Update stack: ${GREEN}serverless deploy --stage $STAGE --region $REGION${NC}"
echo -e "Test API: ${GREEN}curl $API_URL/health${NC}"
echo ""

echo -e "${GREEN}🎉 Deployment completed successfully!${NC}"
